# -*- coding: utf-8 -*-
"""customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBE5KvcS61AzudF0I4Ybg166dij7wDPK

**Dataset:** IBM Watson Telco Customer Churn Dataset

**Objective:** Identify customers likely to churn using statistical analysis and ML models
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.ticker as mtick
import matplotlib.pyplot as plt
# %matplotlib inline

"""##Data Loading and Initial Understanding"""

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

df.head()

df.shape

df.info()

df.describe()

## Statistical Distribution Analysis

#We go beyond basic `.describe()` and examine the **shape** of distributions
#using skewness, kurtosis, and formal normality tests.

from scipy.stats import shapiro

numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df_temp = df.copy()
df_temp['TotalCharges'] = pd.to_numeric(df_temp['TotalCharges'], errors='coerce')

print("=" * 65)
print(f"{'Feature':<18} {'Skewness':>10} {'Kurtosis':>10} {'Shapiro p':>12} {'Normal?':>8}")
print("=" * 65)

for col in numerical_cols:
    series = df_temp[col].dropna()
    skew   = series.skew()
    kurt   = series.kurt()          # excess kurtosis (normal = 0)
    _, p   = shapiro(series.sample(min(5000, len(series)), random_state=42))
    normal = "✅ Yes" if p > 0.05 else "❌ No"
    print(f"{col:<18} {skew:>10.3f} {kurt:>10.3f} {p:>12.4f} {normal:>8}")

print("=" * 65)

"""Interpretation:
  - TotalCharges & tenure: right-skewed (long right tail) → many new customers
  - All three fail Shapiro-Wilk → non-normal distributions
  - This justifies using NON-PARAMETRIC tests (Mann-Whitney U) later

SeniorCitizen is actually a categorical hence the 25%-50%-75% distribution is not propoer

75% customers have tenure less than 55 months

Average Monthly charges are USD 64.76 whereas 25% customers pay more than USD 89.85 per month
"""

ig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, col in zip(axes, numerical_cols):
    series = df_temp[col].dropna()
    ax.hist(series, bins=40, color='steelblue', edgecolor='white', alpha=0.8)
    ax.axvline(series.mean(),   color='red',    linestyle='--', label=f'Mean={series.mean():.1f}')
    ax.axvline(series.median(), color='orange', linestyle='--', label=f'Median={series.median():.1f}')
    ax.set_title(f'{col}\nSkew={series.skew():.2f}')
    ax.legend(fontsize=8)
    ax.set_xlabel(col)
plt.suptitle('Distribution of Numerical Features', y=1.02, fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

df['Churn'].value_counts().plot(kind='barh', figsize=(8, 6))
plt.xlabel("Count", labelpad=14)
plt.ylabel("Target Variable", labelpad=14)
plt.title("Count of TARGET Variable per category", y=1.02);

100*df['Churn'].value_counts()/len(df['Churn'])

df['Churn'].value_counts()

"""* Data is highly imbalanced, ratio = 73:27<br>
* So we analyse the data with other features while taking the target values separately to get some insights.
"""

# Concise Summary of the dataframe, as we have too many columns, we are using the verbose = True mode
df.info(verbose = True)

"""### Missing Data - Initial Intuition

* Here, we don't have any missing data.

General Thumb Rules:

* For features with less missing values- can use regression to predict the missing values or fill with the mean of the values present, depending on the feature.
* For features with very high number of missing values- it is better to drop those columns as they give very less insight on analysis.
* As there's no thumb rule on what criteria do we delete the columns with high number of missing values, but generally you can delete the columns, if you have more than 30-40% of missing values. But again there's a catch here, for example, Is_Car & Car_Type, People having no cars, will obviously have Car_Type as NaN (null), but that doesn't make this column useless, so decisions has to be taken wisely.

# Data Cleaning
"""

df1 = df.copy()

""" Total Charges should be numeric amount. Let's convert it to numerical data type"""

df1.TotalCharges = pd.to_numeric(df1.TotalCharges, errors='coerce')
df1.isnull().sum()

"""As we can see there are 11 missing values in TotalCharges column. Let's check these records"""

df1.loc[df1['TotalCharges'].isnull() == True]

"""## Missing value treatment

Since the percentage of these records compared to total dataset is very low ie 0.15%, it is safe to ignore them from further processing.
"""

#Removing missing values
df1.dropna(how = 'any', inplace = True)

"""Divide customers into bins based on tenure e.g. for tenure < 12 months: assign a tenure group if 1-12, for tenure between 1 to 2 Yrs, tenure group of 13-24; so on..."""

# Get the max tenure
print(df1['tenure'].max()) #72

# Group the tenure in bins of 12 months
labels = ["{0} - {1}".format(i, i + 11) for i in range(1, 72, 12)]

df1['tenure_group'] = pd.cut(df1.tenure, range(1, 80, 12), right=False, labels=labels)

df1['tenure_group'].value_counts()

"""Remove columns not required for processing"""

#drop column customerID and tenure
df1.drop(columns= ['customerID','tenure'], axis=1, inplace=True)
df1.head()

### Chi-Square Test of Independence

# H₀ (Null):** The feature is independent of Churn (no relationship)
# H₁ (Alt):**  The feature is NOT independent of Churn (relationship exists)

# **Cramér's V** measures effect size (0 = no association, 1 = perfect):
#   - V < 0.10 → weak
#   - 0.10–0.30 → moderate
#   - V > 0.30 → strong


import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

def cramers_v(chi2, n, k, r):
    """Cramér's V effect size for chi-square test."""
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

categorical_cols = df_temp.select_dtypes(include='object').columns.tolist()
categorical_cols = [c for c in categorical_cols if c not in ['Churn', 'tenure_group']]

chi2_results = []
for col in categorical_cols:
    ct = pd.crosstab(df_temp[col], df_temp['Churn'])
    chi2, p, dof, _ = chi2_contingency(ct)
    V = cramers_v(chi2, len(df_temp), ct.shape[1], ct.shape[0])
    chi2_results.append(
        {
            'Feature': col,
            'Chi2': round(chi2, 2),
            'p-value': round(p, 4),
            'Cramér V': round(V, 3),
            'Significant (α=0.05)': 'Yes' if p < 0.05 else 'No',
            'Effect Size': 'Strong' if V > 0.3 else ('Moderate' if V > 0.1 else 'Weak'),
        }
    )

chi2_df = pd.DataFrame(chi2_results).sort_values('Cramér V', ascending=False)
print("Chi-Square Test Results (Categorical Features vs Churn):\n")
print(chi2_df.to_string(index=False))

# 6B: Mann-Whitney U Test (Non-Parametric)

# Since our numerical features are NOT normally distributed (confirmed in Section 3),
# we use **Mann-Whitney U** instead of the independent t-test.

# **H₀:** The distribution of the feature is the same for churned and non-churned customers
# **H₁:** The distributions differ significantly

# **Effect size (rank-biserial r):**
#   - |r| < 0.10 → negligible
#   - 0.10–0.30 → small
#   - 0.30–0.50 → medium
#   - |r| > 0.50 → large

from scipy.stats import mannwhitneyu
import numpy as np

df_temp['Churn_binary'] = np.where(df_temp['Churn'] == 'Yes', 1, 0)

num_features = ['MonthlyCharges', 'TotalCharges']
print("\nMann-Whitney U Test Results (Numerical Features vs Churn):\n")
print(f"{'Feature':<18} {'U-statistic':>12} {'p-value':>10} {'Effect r':>10} {'Effect Size':>12} {'Significant':>12}")
print("─" * 76)

for col in num_features:
    churn_yes = df_temp.loc[df_temp['Churn'] == 'Yes', col].dropna()
    churn_no  = df_temp.loc[df_temp['Churn'] == 'No',  col].dropna()
    U, p = mannwhitneyu(churn_yes, churn_no, alternative='two-sided')
    n1, n2 = len(churn_yes), len(churn_no)
    r = 1 - (2 * U) / (n1 * n2)   # rank-biserial correlation
    abs_r = abs(r)
    eff = 'Large' if abs_r > 0.5 else ('Medium' if abs_r > 0.3 else ('Small' if abs_r > 0.1 else 'Negligible'))
    sig = '✅ Yes' if p < 0.05 else '❌ No'
    print(f"{col:<18} {U:>12,.0f} {p:>10.4f} {r:>10.3f} {eff:>12} {sig:>12}")

print("""
Interpretation:
  • MonthlyCharges: Churned customers pay SIGNIFICANTLY higher monthly charges (p < 0.05)
  • TotalCharges: Lower for churned customers → they leave early (short tenure)
""")

plt.figure(figsize=(10, 6))
chi2_df_sorted = chi2_df.sort_values('Cramér V')
colors = ['#e74c3c' if v > 0.1 else '#95a5a6' for v in chi2_df_sorted['Cramér V']]
plt.barh(chi2_df_sorted['Feature'], chi2_df_sorted['Cramér V'], color=colors)
plt.axvline(0.1, color='red', linestyle='--', label='Moderate threshold (V=0.10)')
plt.xlabel("Cramér's V (Effect Size)", fontsize=12)
plt.title("Feature Association with Churn\n(Cramér's V via Chi-Square Test)", fontsize=13, fontweight='bold')
plt.legend()
plt.tight_layout()
plt.show()

print("""
Statistical Feature Ranking (by Cramér's V):
  🔴 HIGH impact  : Contract, OnlineSecurity, TechSupport, InternetService
  🟡 MED impact   : PaymentMethod, PaperlessBilling, OnlineBackup
  ⚪ LOW impact   : Gender, PhoneService, MultipleLines

→ This validates our EDA visually, but now with statistical confidence.
""")

"""#EDA"""

for i, predictor in enumerate(df1.drop(columns=['Churn', 'TotalCharges', 'MonthlyCharges'])):
    plt.figure(figsize=(12, 6))
    sns.countplot(data=df1, x=predictor, hue='Churn')
plt.tight_layout()

"""Convert the target variable 'Churn'  in a binary numeric variable i.e. Yes=1 ; No = 0"""

df1['Churn'] = np.where(df1.Churn == 'Yes',1,0)

df1.head()

"""Converting the categorical variables into dummy variables"""

df1_dummies = pd.get_dummies(df1)
df1_dummies.head()

"""Relationship between Monthly Charges and Total Charges"""

sns.lmplot(data=df1_dummies, x='MonthlyCharges', y='TotalCharges', fit_reg=False)

"""Total Charges increase as Monthly Charges increase - as expected.

Churn by Monthly Charges and Total Charges
"""

Mth = sns.kdeplot(df1_dummies.MonthlyCharges[(df1_dummies["Churn"] == 0) ],
                color="Red", shade = True)
Mth = sns.kdeplot(df1_dummies.MonthlyCharges[(df1_dummies["Churn"] == 1) ],
                ax =Mth, color="Blue", shade= True)
Mth.legend(["No Churn","Churn"],loc='upper right')
Mth.set_ylabel('Density')
Mth.set_xlabel('Monthly Charges')
Mth.set_title('Monthly charges by churn')
plt.show()

"""**Insight:** Churn is high when Monthly Charges ar high"""

Tot = sns.kdeplot(df1_dummies.TotalCharges[(df1_dummies["Churn"] == 0) ],
                color="Red", shade = True)
Tot = sns.kdeplot(df1_dummies.TotalCharges[(df1_dummies["Churn"] == 1) ],
                ax =Tot, color="Blue", shade= True)
Tot.legend(["No Churn","Churn"],loc='upper right')
Tot.set_ylabel('Density')
Tot.set_xlabel('Total Charges')
Tot.set_title('Total charges by churn')

"""**Surprising insight ** as higher Churn at lower Total Charges

However if we combine the insights of 3 parameters i.e. Tenure, Monthly Charges & Total Charges then the picture is bit clear :- Higher Monthly Charge at lower tenure results into lower Total Charge. Hence, all these 3 factors viz **Higher Monthly Charge**,  **Lower tenure** and **Lower Total Charge** are linkd to **High Churn**.

**11. Build a corelation of all predictors with 'Churn' **
"""

plt.figure(figsize=(20,8))
df1_dummies.corr()['Churn'].sort_values(ascending = False).plot(kind='bar')

"""**Derived Insight: **

**HIGH** Churn seen in case of  **Month to month contracts**, **No online security**, **No Tech support**, **First year of subscription** and **Fibre Optics Internet**

**LOW** Churn is seens in case of **Long term contracts**, **Subscriptions without internet service** and **The customers engaged for 5+ years**

Factors like **Gender**, **Availability of PhoneService** and **# of multiple lines** have alomost **NO** impact on Churn

This is also evident from the **Heatmap** below
"""

plt.figure(figsize=(12,12))
sns.heatmap(df1_dummies.corr(), cmap="Paired")

"""##Bivariate Analysis"""

new_df1_target0=df1.loc[df1["Churn"]==0]
new_df1_target1=df1.loc[df1["Churn"]==1]

def uniplot(df,col,title,hue =None):

    sns.set_style('whitegrid')
    sns.set_context('talk')
    plt.rcParams["axes.labelsize"] = 20
    plt.rcParams['axes.titlesize'] = 22
    plt.rcParams['axes.titlepad'] = 30


    temp = pd.Series(data = hue)
    fig, ax = plt.subplots()
    width = len(df[col].unique()) + 7 + 4*len(temp.unique())
    fig.set_size_inches(width , 8)
    plt.xticks(rotation=45)
    plt.yscale('log')
    plt.title(title)
    ax = sns.countplot(data = df, x= col, order=df[col].value_counts().index,hue = hue,palette='bright')

    plt.show()

uniplot(new_df1_target1,col='Partner',title='Distribution of Gender for Churned Customers',hue='gender')

uniplot(new_df1_target0,col='Partner',title='Distribution of Gender for Non Churned Customers',hue='gender')

uniplot(new_df1_target1,col='PaymentMethod',title='Distribution of PaymentMethod for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='Contract',title='Distribution of Contract for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='TechSupport',title='Distribution of TechSupport for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='SeniorCitizen',title='Distribution of SeniorCitizen for Churned Customers',hue='gender')

"""# CONCLUSION

These are some of the quick insights from this exercise:

1. Electronic check medium are the highest churners
2. Contract Type - Monthly customers are more likely to churn because of no contract terms, as they are free to go customers.
3. No Online security, No Tech Support category are high churners
4. Non senior Citizens are high churners

Note: There could be many more such insights, so take this as an assignment and try to get more insights :)

# **MODEL BUILDING**
"""

import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

df2=df1_dummies.copy()

df2.head()

X=df2.drop('Churn',axis=1)
X

y=df2['Churn']
y

"""Train-Test Split"""

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

"""## Decision Tree Classifier"""

model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

model_dt.fit(X_train,y_train)

y_pred=model_dt.predict(X_test)
y_pred

model_dt.score(X_test,y_test)

print(classification_report(y_test, y_pred, labels=[0,1]))

"""- As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datase
 - Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.

- Hence, moving ahead to call SMOTEENN (UpSampling + ENN)
"""

sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(X,y)

xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

print(metrics.confusion_matrix(yr_test, yr_predict))

"""- Now we can see quite better results, i.e. Accuracy: 92 %, and a very good recall, precision & f1 score for minority class.

"""

from sklearn.ensemble import RandomForestClassifier

model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

model_rf.fit(X_train,y_train)

y_pred=model_rf.predict(X_test)

model_rf.score(X_test,y_test)

print(classification_report(y_test, y_pred, labels=[0,1]))

sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(X,y)

xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

model_rf_smote.fit(xr_train1,yr_train1)

yr_predict1 = model_rf_smote.predict(xr_test1)

model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

print(metrics.confusion_matrix(yr_test1, yr_predict1))

import pickle

filename = 'model.sav'

pickle.dump(model_rf_smote, open(filename, 'wb'))

load_model = pickle.load(open(filename, 'rb'))

model_score_r1 = load_model.score(xr_test1, yr_test1)

model_score_r1

import pickle

# Save feature columns — MUST match training data
feature_columns = list(X.columns)
pickle.dump(feature_columns, open('feature_columns.pkl', 'wb'))

# Also re-save your model cleanly
pickle.dump(model_rf_smote, open('model.sav', 'wb'))

"""##### Our final model i.e. RF Classifier with SMOTEENN, is now ready and dumped in model.sav, which we will use and prepare API's so that we can access our model from UI.

## Saving the Model for Deployment
"""

import sklearn; print(sklearn.__version__)

import sklearn
import imblearn
print(sklearn.__version__)   # should show 1.6.1
print(imblearn.__version__)  # note this version too

import pickle
feature_columns = list(X.columns)
pickle.dump(feature_columns, open('feature_columns.pkl', 'wb'))

